#!/bin/bash

day=`date "+%d"`

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Set ruby version
RUBY_VERSION=2.0.0-p247

# Install ruby version
rvm install ruby-$RUBY_VERSION --disable-binary --verify-downloads 1

# Set ruby / gemset
rvm use $RUBY_VERSION@simple_deploy --create

# Reload RVM to fix Seg Fault that was going to drive Weaver instance
rvm reload

# Install new version of simple_deploy
bundle install
rake install

echo simple_deploy envs --------------
simple_deploy envs
  
echo simple_deploy list --------------
simple_deploy list -e default

echo simple_deploy failure --------------
simple_deploy clone -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy create --------------
#  simple_deploy create -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy instances --------------
#  simple_deploy instances -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy attributes --------------
#  simple_deploy attributes -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy outputs --------------
#  simple_deploy outputs -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy resources --------------
#  simple_deploy resources -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy template --------------
#  simple_deploy template -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy status --------------
#  simple_deploy status -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy events --------------
#  simple_deploy events -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy deploy --------------
#  simple_deploy deploy -e default -n jenkins-test-stack -a app=c1e025a5d5702bfcee42b2b742d466e6ad18d393 -f

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy update --------------
#  simple_deploy update -e default -n jenkins-test-stack -a jenkins_test_val=testvalue

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy update --------------
#  simple_deploy update -e default -n jenkins-test-stack -a jenkins_test_val=nil

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy deploy --------------
#  simple_deploy deploy -e default -n jenkins-test-stack -a app=c1e025a5d5702bfcee42b2b742d466e6ad18d393

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

echo simple_deploy destroy --------------
#  simple_deploy destroy -e default -n jenkins-test-stack

if [ $? -ne 0 ]; then
  EXITSTATUS=1
fi

exit $EXITSTATUS
